name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          # Set up the SSH directory
          mkdir -p ~/.ssh
          
          # Add the server's SSH key to known_hosts (avoids 'Host key verification failed' error)
          ssh-keyscan -H 54.92.36.139 >> ~/.ssh/known_hosts

          # Write the private key from GitHub Secrets into ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa

          # Set the correct permissions for the private key
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy WordPress
        run: |
          rsync -avz --exclude '.git' --delete ./ github@54.92.36.139:/var/www/html/wordpress
          ssh github@54.92.36.139 'sudo systemctl reload nginx'
