name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 54.92.36.139 >> ~/.ssh/known_hosts

      - name: Deploy WordPress using SCP
        run: |
          scp -r ./ github@54.92.36.139:/var/www/html/wordpress

      - name: Reload nginx
        run: |
          ssh github@54.92.36.139 'sudo systemctl reload nginx'
