name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy WordPress
        run: |
          rsync -avz --exclude '.git' --delete ./ github@54.92.36.139:/var/www/html/wordpress
          ssh github@54.92.36.139 'sudo systemctl reload nginx'
